# Generated by Django 4.1 on 2023-10-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='id',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
